# This is a basic workflow to help you get started with Actions
name: Check the pull requests
# Controls when the workflow will run
on:
  pull_request_target:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - run: echo ${{ secrets.FLAG2 }}
      
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      
      - name: Install required dependencies
        run: npm ci
      - name: Run the tests
        run: npm test
